categs_dict = {
    'Cheese': 'cheese',
    'Cheese - Block': 'cheese',
    'Cheese/Cheese Substitutes': 'cheese',
    'Cheese - Speciality': 'cheese',
    'Breads & Buns': 'bread',
    # 'Dried Breads (Shelf Stable)': 'bread',
    'Bread': 'bread',
    'Bread (Frozen)': 'bread',
    'Bread (Shelf Stable)': 'bread',
    'Frozen Bread & Dough': 'bread',
    'Yogurt': 'yogurt',
    'Yogurt/Yogurt Substitutes': 'yogurt',
    'Yogurt (Perishable)': 'yogurt',
    'Yogurt/Yogurt Substitutes (Perishable)': 'yogurt',
    'Milk': 'milk',
    'Plant Based Milk': 'milk',
    'Milk/Milk Substitutes': 'milk',
    'Canned Vegetables': 'vegetable',
    'Frozen Vegetables': 'vegetable',
    'Vegetables  Unprepared/Unprocessed (Frozen)': 'vegetable',
    'Vegetables': 'vegetable',
    # 'Pepperoni, Salami & Cold Cuts': 'meat',
    'Sausages, Hotdogs & Brats': 'meat',
    # 'Bacon, Sausages & Ribs': 'meat',
    'Meat/Poultry/Other Animals  Unprepared/Unprocessed': 'meat',
    'Canned Meat': 'meat',
    'Other Meats': 'meat',
    'Other Frozen Meats': 'meat',
    # 'Poultry, Chicken & Turkey': 'meat',
    # 'Frozen Poultry, Chicken & Turkey': 'meat',
    'Vegetarian Frozen Meats': 'meat',
    'Meat/Poultry/Other Animals – Unprepared/Unprocessed': 'meat',
    'Chicken - Unprepared/Unprocessed': 'meat',
    'Meat Substitutes': 'meat',
    'Frozen Meat': 'meat',
    'Salami / Cured Meat': 'meat',
    'Fresh Meat': 'meat',
    'Vegetable & Cooking Oils': 'oil',
    'Oils Edible': 'oil',
    'Oils Edible - Vegetable or Plant (Shelf Stable)': 'oil',
    'Fruit': 'fruit',
    'Canned Fruit': 'fruit',
    'Frozen Fruit': 'fruit',
    'Frozen Fruit & Fruit Juice Concentrates': 'fruit',
    'Fruits  Unprepared/Unprocessed (Frozen)': 'fruit',
    'Frozen Fish & Seafood': 'seafood',
    'Frozen Fish/Seafood': 'seafood',
    'Fish  Unprepared/Unprocessed': 'seafood',
    'Fish – Unprepared/Unprocessed': 'seafood',
    'Canned Seafood': 'seafood',
    'Shellfish Unprepared/Unprocessed': 'seafood',
    'Honey': 'honey',
    'Eggs & Egg Substitutes': 'egg',
    'Eggs/Eggs Substitutes': 'egg',
    'Eggs Products/Substitutes': 'egg',
    'Eggs': 'egg',
    # 'Coffee': 'coffee',
    # 'Coffee/Tea/Substitutes': 'coffee',
    'Butter/Butter Substitutes': 'butter',
    'Butter & Spread': 'butter',
}

flavor_df_columns_defined = [
    'taste',
    'functional_groups',
    'fooddb_flavor_profile',
    'supersweetdb_id',
    'fooddb_id',
    'common_name',
    'bitterdb_id',
    'super_sweet',
    'flavornet_id',
    'pubchem_id',
    'bitter',
    'iupac_name',
    'odor',
    'smile',
    'inchi',
    'cas_id',
    'flavor_profile',
    'fema_flavor_profile',
]
